CREATE TABLE ROOM (
  ROOM_ID          NUMBER,
  CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID),
  NUM_GUESTS       NUMBER       NOT NULL,
  PRICE            NUMBER(*, 2) NOT NULL,
  BREAKFAST_INCLUD NUMBER(1) DEFAULT 0 CHECK (BREAKFAST_INCLUD = 0 OR BREAKFAST_INCLUD = 1),
  PETS_ALLOW       NUMBER(1) DEFAULT 0 CHECK (PETS_ALLOW = 0 OR PETS_ALLOW = 1),
  DATE_FROM        DATE,
  HOTEL         NUMBER,
  CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL) REFERENCES HOTEL_SECOND (HOTEL_ID)
);